window:
  padding:
    x: 16
    y: 16
font:
  normal:
    family: VictorMono Nerd Font
    style: Regular
  bold:
    family: VictorMono Nerd Font
    style: Bold
  italic:
    family: VictorMono Nerd Font
    style: Italic
  size: 13

  offset:
    x: 0
    y: 0
cursor:
  style:
    shape: Beam
    blinking: On
    blink-interval: 2
colors:
  primary:
    # background: "#161821"
    # foreground: "#c6c8d1"
    foreground: "#E8E9ED"
    background: "#383C4A"
  cursor:
    text: '0x002b36'
    cursor: '0xFFC759'
  normal:
    black:   '0x002b36'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x058ED9'
    magenta: '0x6c71c4'
    cyan:    '0x2aa198'
    white:   '0x93a1a1'
